// @ts-nocheck
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getSubscriptions: () => typedError<Subscription[], AppError>(__TAURI_INVOKE("get_subscriptions")),
	addSubscription: (subscription: CreateSubscription) => typedError<Subscription, AppError>(__TAURI_INVOKE("add_subscription", { subscription })),
	removeSubscription: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("remove_subscription", { id })),
	toggleMute: (id: string) => typedError<Subscription, AppError>(__TAURI_INVOKE("toggle_mute", { id })),
	getNotifications: (subscriptionId: string) => typedError<Notification[], AppError>(__TAURI_INVOKE("get_notifications", { subscriptionId })),
	markAsRead: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("mark_as_read", { id })),
	markAllAsRead: (subscriptionId: string) => typedError<null, AppError>(__TAURI_INVOKE("mark_all_as_read", { subscriptionId })),
	deleteNotification: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_notification", { id })),
	setNotificationExpanded: (id: string, expanded: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_notification_expanded", { id, expanded })),
	getUnreadCount: (subscriptionId: string) => typedError<number, AppError>(__TAURI_INVOKE("get_unread_count", { subscriptionId })),
	getTotalUnreadCount: () => typedError<number, AppError>(__TAURI_INVOKE("get_total_unread_count")),
	getIgnoreRules: () => typedError<IgnoreRule[], AppError>(__TAURI_INVOKE("get_ignore_rules")),
	addIgnoreRule: (pattern: string, subscriptionId: string | null) => typedError<IgnoreRule, AppError>(__TAURI_INVOKE("add_ignore_rule", { pattern, subscriptionId })),
	deleteIgnoreRule: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_ignore_rule", { id })),
	getSettings: () => typedError<AppSettings, AppError>(__TAURI_INVOKE("get_settings")),
	setTheme: (theme: ThemeMode) => typedError<null, AppError>(__TAURI_INVOKE("set_theme", { theme })),
	addServer: (server: ServerConfig) => typedError<null, AppError>(__TAURI_INVOKE("add_server", { server })),
	removeServer: (url: string) => typedError<null, AppError>(__TAURI_INVOKE("remove_server", { url })),
	setDefaultServer: (url: string) => typedError<null, AppError>(__TAURI_INVOKE("set_default_server", { url })),
	setMinimizeToTray: (enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_minimize_to_tray", { enabled })),
	setStartMinimized: (enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_start_minimized", { enabled })),
	setNotificationMethod: (method: NotificationDisplayMethod) => typedError<null, AppError>(__TAURI_INVOKE("set_notification_method", { method })),
	setNotificationForceDisplay: (enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_notification_force_display", { enabled })),
	setNotificationShowActions: (enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_notification_show_actions", { enabled })),
	setNotificationShowImages: (enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_notification_show_images", { enabled })),
	setNotificationSound: (enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_notification_sound", { enabled })),
	setCompactView: (enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_compact_view", { enabled })),
	setExpandNewMessages: (enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_expand_new_messages", { enabled })),
	setDeleteLocalOnly: (enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_delete_local_only", { enabled })),
	setFavoritesEnabled: (enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_favorites_enabled", { enabled })),
	setNotificationFavorite: (id: string, favorite: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_notification_favorite", { id, favorite })),
	getFavoriteNotifications: () => typedError<Notification[], AppError>(__TAURI_INVOKE("get_favorite_notifications")),
	/**  Sync subscriptions from a server that has user credentials */
	syncSubscriptions: (serverUrl: string) => typedError<Subscription[], AppError>(__TAURI_INVOKE("sync_subscriptions", { serverUrl })),
	/**
	 *  Check for available updates.
	 * 
	 *  Returns update information if an update is available, null otherwise.
	 */
	checkForUpdate: () => typedError<{
	/**  The new version available. */
	version: string,
	/**  The current installed version. */
	current_version: string,
	/**  Release notes for the update. */
	body: string | null,
	/**  Release date. */
	date: string | null,
} | null, AppError>(__TAURI_INVOKE("check_for_update")),
	/**
	 *  Download and install an available update.
	 * 
	 *  This will download the update and may restart the application.
	 */
	installUpdate: () => typedError<null, AppError>(__TAURI_INVOKE("install_update")),
	/**  Get the current application version. */
	getAppVersion: () => __TAURI_INVOKE<string>("get_app_version"),
	/**
	 *  Get the application version for display purposes.
	 * 
	 *  Returns "dev" in debug builds, "vX.Y.Z" in release builds.
	 */
	getAppVersionDisplay: () => __TAURI_INVOKE<string>("get_app_version_display"),
};

/* Types */
/**
 *  Application error type that serializes to a discriminated union in TypeScript.
 * 
 *  The derive(Serialize) produces the externally tagged format that matches
 *  the TypeScript type generated by specta:
 *  ```typescript
 *  type AppError = { Database: string } | { WebSocket: string } | ...
 *  ```
 */
export type AppError = ({ Database: string }) & { Connection?: never; Credential?: never; InvalidUrl?: never; NotFound?: never; Serialization?: never; Updater?: never; Validation?: never; WebSocket?: never } | ({ WebSocket: string }) & { Connection?: never; Credential?: never; Database?: never; InvalidUrl?: never; NotFound?: never; Serialization?: never; Updater?: never; Validation?: never } | ({ Serialization: string }) & { Connection?: never; Credential?: never; Database?: never; InvalidUrl?: never; NotFound?: never; Updater?: never; Validation?: never; WebSocket?: never } | ({ NotFound: string }) & { Connection?: never; Credential?: never; Database?: never; InvalidUrl?: never; Serialization?: never; Updater?: never; Validation?: never; WebSocket?: never } | ({ Validation: string }) & { Connection?: never; Credential?: never; Database?: never; InvalidUrl?: never; NotFound?: never; Serialization?: never; Updater?: never; WebSocket?: never } | ({ InvalidUrl: string }) & { Connection?: never; Credential?: never; Database?: never; NotFound?: never; Serialization?: never; Updater?: never; Validation?: never; WebSocket?: never } | ({ Connection: string }) & { Credential?: never; Database?: never; InvalidUrl?: never; NotFound?: never; Serialization?: never; Updater?: never; Validation?: never; WebSocket?: never } | ({ Credential: string }) & { Connection?: never; Database?: never; InvalidUrl?: never; NotFound?: never; Serialization?: never; Updater?: never; Validation?: never; WebSocket?: never } | ({ Updater: string }) & { Connection?: never; Credential?: never; Database?: never; InvalidUrl?: never; NotFound?: never; Serialization?: never; Validation?: never; WebSocket?: never };

/**  Application-wide settings. */
export type AppSettings = {
	/**  Theme mode for the application. */
	theme: ThemeMode,
	/**  Configured ntfy servers. */
	servers: ServerConfig[],
	/**  URL of the default server for new subscriptions. */
	defaultServer: string,
	/**  Minimize to tray instead of closing. */
	minimizeToTray?: boolean,
	/**  Start application minimized to tray. */
	startMinimized?: boolean,
	/**  Notification display method. */
	notificationMethod?: NotificationDisplayMethod,
	/**  Force display even when Focus Assist is on (Windows Enhanced only). */
	notificationForceDisplay?: boolean,
	/**  Show action buttons in notification (Windows Enhanced only). */
	notificationShowActions?: boolean,
	/**  Show images in notification (Windows Enhanced only). */
	notificationShowImages?: boolean,
	/**  Play notification sound. */
	notificationSound?: boolean,
	/**  Show messages in collapsed accordion style. */
	compactView?: boolean,
	/**  Automatically expand newly received messages (when compact view is enabled). */
	expandNewMessages?: boolean,
	/**  Delete notifications only locally (when disabled, also deletes from ntfy server). */
	deleteLocalOnly?: boolean,
	/**  Enable favorites feature (star icon on notifications). */
	favoritesEnabled?: boolean,
};

/**  A file attachment on a notification. */
export type Attachment = {
	id: string,
	name: string,
	type: string,
	url: string,
	size: number | null,
};

/**  Data required to create a new subscription. */
export type CreateSubscription = {
	topic: string,
	serverUrl: string,
	displayName: string | null,
};

/**
 *  A rule hiding notifications whose title contains `pattern`.
 * 
 *  `subscription_id` of `None` means the rule applies to every topic.
 */
export type IgnoreRule = {
	id: string,
	pattern: string,
	subscriptionId: string | null,
	/**  Unix timestamp in milliseconds. */
	createdAt: number,
};

/**  A notification stored in the local database. */
export type Notification = {
	id: string,
	topicId: string,
	title: string,
	message: string,
	/**  Priority level (1-5): 1=min, 2=low, 3=default, 4=high, 5=max. */
	priority: number,
	tags: string[],
	/**
	 *  Unix timestamp in milliseconds.
	 *  Exported as a TS `number`: safe for millisecond timestamps until year 285,616.
	 */
	timestamp: number,
	actions: NotificationAction[],
	attachments: Attachment[],
	read: boolean,
	/**  Whether the notification is expanded in compact view mode. */
	isExpanded: boolean,
	/**  Whether the notification is marked as favorite. */
	isFavorite: boolean,
};

/**  An action button attached to a notification. */
export type NotificationAction = {
	id: string,
	label: string,
	url: string | null,
	method: string | null,
	clear: boolean,
};

/**  Notification display method. */
export type NotificationDisplayMethod = 
/**  Standard cross-platform notifications (may be suppressed by Focus Assist). */
"native" | 
/**  Windows-specific enhanced notifications with action buttons and force display. */
"windows_enhanced";

/**  Configuration for a single ntfy server. */
export type ServerConfig = {
	url: string,
	username: string | null,
	password: string | null,
	isDefault: boolean,
};

/**  A subscription to a topic on an ntfy server. */
export type Subscription = {
	id: string,
	topic: string,
	serverUrl: string,
	displayName: string | null,
	unreadCount: number,
	/**  Timestamp of the most recent notification (milliseconds). */
	lastNotification: number | null,
	/**  Whether notifications from this subscription are muted. */
	muted: boolean,
};

/**  Theme mode for the application. */
export type ThemeMode = "light" | "dark" | "system";

/**  Information about an available update. */
export type UpdateInfo = {
	/**  The new version available. */
	version: string,
	/**  The current installed version. */
	current_version: string,
	/**  Release notes for the update. */
	body: string | null,
	/**  Release date. */
	date: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

