
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getSubscriptions() : Promise<Result<Subscription[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_subscriptions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addSubscription(subscription: CreateSubscription) : Promise<Result<Subscription, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_subscription", { subscription }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeSubscription(id: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_subscription", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleMute(id: string) : Promise<Result<Subscription, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_mute", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getNotifications(subscriptionId: string) : Promise<Result<Notification[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_notifications", { subscriptionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async markAsRead(id: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_as_read", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async markAllAsRead(subscriptionId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_all_as_read", { subscriptionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteNotification(id: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_notification", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getUnreadCount(subscriptionId: string) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_unread_count", { subscriptionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTotalUnreadCount() : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_total_unread_count") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<Result<AppSettings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTheme(theme: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_theme", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addServer(server: ServerConfig) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_server", { server }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeServer(url: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_server", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setDefaultServer(url: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_default_server", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setMinimizeToTray(enabled: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_minimize_to_tray", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setStartMinimized(enabled: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_start_minimized", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sync subscriptions from a server that has user credentials
 */
async syncSubscriptions(serverUrl: string) : Promise<Result<Subscription[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_subscriptions", { serverUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppError = { Database: string } | { WebSocket: string } | { Serialization: string } | { NotFound: string } | { InvalidUrl: string } | { Connection: string } | { Credential: string }
/**
 * Application-wide settings.
 */
export type AppSettings = { 
/**
 * Theme ID or "system" for automatic.
 */
theme: string; 
/**
 * Configured ntfy servers.
 */
servers: ServerConfig[]; 
/**
 * URL of the default server for new subscriptions.
 */
defaultServer: string; 
/**
 * Minimize to tray instead of closing.
 */
minimizeToTray?: boolean; 
/**
 * Start application minimized to tray.
 */
startMinimized?: boolean }
/**
 * A file attachment on a notification.
 */
export type Attachment = { id: string; name: string; type: string; url: string; size: number | null }
/**
 * Data required to create a new subscription.
 */
export type CreateSubscription = { topic: string; serverUrl: string; displayName: string | null }
/**
 * A notification stored in the local database.
 */
export type Notification = { id: string; topicId: string; title: string; message: string; priority: Priority; tags: string[]; 
/**
 * Unix timestamp in milliseconds.
 */
timestamp: number; actions: NotificationAction[]; attachments: Attachment[]; read: boolean }
/**
 * An action button attached to a notification.
 */
export type NotificationAction = { id: string; label: string; url: string | null; method: string | null; clear: boolean }
/**
 * Notification priority levels matching ntfy's 1-5 scale.
 */
export type Priority = "Min" | "Low" | "Default" | "High" | "Max"
/**
 * Configuration for a single ntfy server.
 */
export type ServerConfig = { url: string; username: string | null; password: string | null; isDefault: boolean }
/**
 * A subscription to a topic on an ntfy server.
 */
export type Subscription = { id: string; topic: string; serverUrl: string; displayName: string | null; unreadCount: number; 
/**
 * Timestamp of the most recent notification (milliseconds).
 */
lastNotification: number | null; 
/**
 * Whether notifications from this subscription are muted.
 */
muted: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
