// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getSubscriptions() : Promise<Result<Subscription[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_subscriptions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addSubscription(subscription: CreateSubscription) : Promise<Result<Subscription, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_subscription", { subscription }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeSubscription(id: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_subscription", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleMute(id: string) : Promise<Result<Subscription, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_mute", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getNotifications(subscriptionId: string) : Promise<Result<Notification[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_notifications", { subscriptionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async markAsRead(id: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_as_read", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async markAllAsRead(subscriptionId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_all_as_read", { subscriptionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteNotification(id: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_notification", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setNotificationExpanded(id: string, expanded: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_notification_expanded", { id, expanded }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getUnreadCount(subscriptionId: string) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_unread_count", { subscriptionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTotalUnreadCount() : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_total_unread_count") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<Result<AppSettings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTheme(theme: ThemeMode) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_theme", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addServer(server: ServerConfig) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_server", { server }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeServer(url: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_server", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setDefaultServer(url: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_default_server", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setMinimizeToTray(enabled: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_minimize_to_tray", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setStartMinimized(enabled: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_start_minimized", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setNotificationMethod(method: NotificationDisplayMethod) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_notification_method", { method }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setNotificationForceDisplay(enabled: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_notification_force_display", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setNotificationShowActions(enabled: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_notification_show_actions", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setNotificationShowImages(enabled: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_notification_show_images", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setNotificationSound(enabled: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_notification_sound", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setCompactView(enabled: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_compact_view", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setExpandNewMessages(enabled: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_expand_new_messages", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setDeleteLocalOnly(enabled: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_delete_local_only", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sync subscriptions from a server that has user credentials
 */
async syncSubscriptions(serverUrl: string) : Promise<Result<Subscription[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_subscriptions", { serverUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check for available updates.
 * 
 * Returns update information if an update is available, null otherwise.
 */
async checkForUpdate() : Promise<Result<UpdateInfo | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_for_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Download and install an available update.
 * 
 * This will download the update and may restart the application.
 */
async installUpdate() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current application version.
 */
async getAppVersion() : Promise<string> {
    return await TAURI_INVOKE("get_app_version");
},
/**
 * Get the application version for display purposes.
 * 
 * Returns "dev" in debug builds, "vX.Y.Z" in release builds.
 */
async getAppVersionDisplay() : Promise<string> {
    return await TAURI_INVOKE("get_app_version_display");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Application error type that serializes to a discriminated union in TypeScript.
 * 
 * The derive(Serialize) produces the externally tagged format that matches
 * the TypeScript type generated by specta:
 * ```typescript
 * type AppError = { Database: string } | { WebSocket: string } | ...
 * ```
 */
export type AppError = { Database: string } | { WebSocket: string } | { Serialization: string } | { NotFound: string } | { InvalidUrl: string } | { Connection: string } | { Credential: string } | { Updater: string }
/**
 * Application-wide settings.
 */
export type AppSettings = { 
/**
 * Theme mode for the application.
 */
theme: ThemeMode; 
/**
 * Configured ntfy servers.
 */
servers: ServerConfig[]; 
/**
 * URL of the default server for new subscriptions.
 */
defaultServer: string; 
/**
 * Minimize to tray instead of closing.
 */
minimizeToTray?: boolean; 
/**
 * Start application minimized to tray.
 */
startMinimized?: boolean; 
/**
 * Notification display method.
 */
notificationMethod?: NotificationDisplayMethod; 
/**
 * Force display even when Focus Assist is on (Windows Enhanced only).
 */
notificationForceDisplay?: boolean; 
/**
 * Show action buttons in notification (Windows Enhanced only).
 */
notificationShowActions?: boolean; 
/**
 * Show images in notification (Windows Enhanced only).
 */
notificationShowImages?: boolean; 
/**
 * Play notification sound.
 */
notificationSound?: boolean; 
/**
 * Show messages in collapsed accordion style.
 */
compactView?: boolean; 
/**
 * Automatically expand newly received messages (when compact view is enabled).
 */
expandNewMessages?: boolean; 
/**
 * Delete notifications only locally (when disabled, also deletes from ntfy server).
 */
deleteLocalOnly?: boolean }
/**
 * A file attachment on a notification.
 */
export type Attachment = { id: string; name: string; type: string; url: string; size: number | null }
/**
 * Data required to create a new subscription.
 */
export type CreateSubscription = { topic: string; serverUrl: string; displayName: string | null }
/**
 * A notification stored in the local database.
 */
export type Notification = { id: string; topicId: string; title: string; message: string; 
/**
 * Priority level (1-5): 1=min, 2=low, 3=default, 4=high, 5=max.
 */
priority: number; tags: string[]; 
/**
 * Unix timestamp in milliseconds.
 */
timestamp: number; actions: NotificationAction[]; attachments: Attachment[]; read: boolean; 
/**
 * Whether the notification is expanded in compact view mode.
 */
isExpanded: boolean }
/**
 * An action button attached to a notification.
 */
export type NotificationAction = { id: string; label: string; url: string | null; method: string | null; clear: boolean }
/**
 * Notification display method.
 */
export type NotificationDisplayMethod = 
/**
 * Standard cross-platform notifications (may be suppressed by Focus Assist).
 */
"native" | 
/**
 * Windows-specific enhanced notifications with action buttons and force display.
 */
"windows_enhanced"
/**
 * Configuration for a single ntfy server.
 */
export type ServerConfig = { url: string; username: string | null; password: string | null; isDefault: boolean }
/**
 * A subscription to a topic on an ntfy server.
 */
export type Subscription = { id: string; topic: string; serverUrl: string; displayName: string | null; unreadCount: number; 
/**
 * Timestamp of the most recent notification (milliseconds).
 */
lastNotification: number | null; 
/**
 * Whether notifications from this subscription are muted.
 */
muted: boolean }
/**
 * Theme mode for the application.
 */
export type ThemeMode = "light" | "dark" | "system"
/**
 * Information about an available update.
 */
export type UpdateInfo = { 
/**
 * The new version available.
 */
version: string; 
/**
 * The current installed version.
 */
current_version: string; 
/**
 * Release notes for the update.
 */
body: string | null; 
/**
 * Release date.
 */
date: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
