use serde::Serialize;
use specta::Type;
use thiserror::Error;

/// Application error type that serializes to a discriminated union in TypeScript.
///
/// The derive(Serialize) produces the externally tagged format that matches
/// the TypeScript type generated by specta:
/// ```typescript
/// type AppError = { Database: string } | { WebSocket: string } | ...
/// ```
#[allow(dead_code)]
#[derive(Error, Debug, Type, Serialize)]
pub enum AppError {
    #[error("Database error: {0}")]
    Database(String),

    #[error("WebSocket error: {0}")]
    WebSocket(String),

    #[error("Serialization error: {0}")]
    Serialization(String),

    #[error("Not found: {0}")]
    NotFound(String),

    #[error("Invalid URL: {0}")]
    InvalidUrl(String),

    #[error("Connection error: {0}")]
    Connection(String),

    #[error("Credential error: {0}")]
    Credential(String),
}

// Conversion from rusqlite::Error
impl From<rusqlite::Error> for AppError {
    fn from(err: rusqlite::Error) -> Self {
        AppError::Database(err.to_string())
    }
}

// Conversion from serde_json::Error
impl From<serde_json::Error> for AppError {
    fn from(err: serde_json::Error) -> Self {
        AppError::Serialization(err.to_string())
    }
}
