use serde::Serialize;
use specta::Type;
use thiserror::Error;

/// Application error type that serializes to a discriminated union in TypeScript.
///
/// The derive(Serialize) produces the externally tagged format that matches
/// the TypeScript type generated by specta:
/// ```typescript
/// type AppError = { Database: string } | { WebSocket: string } | ...
/// ```
#[allow(dead_code)]
#[derive(Error, Debug, Type, Serialize)]
pub enum AppError {
    #[error("Database error: {0}")]
    Database(String),

    #[error("WebSocket error: {0}")]
    WebSocket(String),

    #[error("Serialization error: {0}")]
    Serialization(String),

    #[error("Not found: {0}")]
    NotFound(String),

    #[error("Invalid URL: {0}")]
    InvalidUrl(String),

    #[error("Connection error: {0}")]
    Connection(String),

    #[error("Credential error: {0}")]
    Credential(String),

    #[error("Updater error: {0}")]
    Updater(String),
}

// Conversion from Diesel errors — log full detail, return generic message to frontend
impl From<diesel::result::Error> for AppError {
    fn from(err: diesel::result::Error) -> Self {
        log::error!("Diesel error: {err}");
        match err {
            diesel::result::Error::NotFound => {
                Self::NotFound("Requested resource not found".to_string())
            }
            _ => Self::Database("Database operation failed".to_string()),
        }
    }
}

impl From<diesel::ConnectionError> for AppError {
    fn from(err: diesel::ConnectionError) -> Self {
        log::error!("Diesel connection error: {err}");
        Self::Database("Database connection failed".to_string())
    }
}

impl<T> From<std::sync::PoisonError<T>> for AppError {
    fn from(err: std::sync::PoisonError<T>) -> Self {
        Self::Database(format!("Mutex poisoned: {err}"))
    }
}

// Conversion from serde_json::Error
impl From<serde_json::Error> for AppError {
    fn from(err: serde_json::Error) -> Self {
        Self::Serialization(err.to_string())
    }
}
